- name: restart strongswan
  service: name=strongswan state=restarted

- name: daemon-reload
  shell: systemctl daemon-reload

- name: restart apparmor
  service: name=apparmor state=restarted

- name: save iptables
  shell: service netfilter-persistent save

- name: restart iptables
  service: name=netfilter-persistent state=restarted

- name: rereadcrls
  shell: ipsec rereadcrls; ipsec purgecrls

- name: restart centos iptables
  service: name=iptables state=restarted

- name: restart centos ip6tables
  service: name=ip6tables state=restarted