- name: CentOS | Install prerequisites
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - epel-release
      - yum-utils

- lineinfile:
    path: /etc/protocols
    line: 'ipencap	4	IP-ENCAP	# IP encapsulated in IP (officially "IP")'
